baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: 'Gillian Vandewyer Portfolio'
primary: true
siteGroup: b88df587-5191-414e-bf0d-9d0a26f8c51a # Gillian Vandewyer Portfolio
sortOrder: 1
