contentColumnType: string
fieldGroup: 3d4894b5-b5aa-4eff-86d3-9dd7913614dc # Work
handle: modelfileposter
instructions: ''
name: modelFilePoster
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds: null
  defaultUploadLocationSource: 'volume:1e5f77d8-5843-4b3f-ac7e-0d9d0a8d489b' # General
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: ''
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:1e5f77d8-5843-4b3f-ac7e-0d9d0a8d489b' # General
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
